=== meta-mart/metamart/metamart-spec/src/main/resources/json/schema/entity/applications/createAppRequest.json
{
  "$id": "https://meta-mart.org/schema/entity/applications/createAppRequest.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CreateAppRequest",
  "javaType": "org.metamart.schema.entity.app.CreateApp",
  "javaInterfaces": ["org.metamart.schema.CreateEntity"],
  "description": "This schema defines the create applications request for Meta-Mart.",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the Application.",
      "$ref": "../../type/basic.json#/definitions/entityName"
    },
    "displayName": {
      "description": "Display Name for the application.",
      "type": "string"
    },
    "description": {
      "description": "Description of the Application.",
      "$ref": "../../type/basic.json#/definitions/markdown"
    },
    "owners": {
      "description": "Owners of this workflow.",
      "$ref": "../../type/entityReferenceList.json",
      "default": null
    },
    "bot": {
      "description": "Fqn of Bot Associated with this application.",
      "$ref": "../../type/basic.json#/definitions/fullyQualifiedEntityName",
      "default": null
    },
    "appConfiguration": {
      "description": "Application Configuration object."
    },
    "appSchedule": {
      "$ref": "./app.json#/definitions/appSchedule"
    },
    "domain" : {
      "description": "Fully qualified name of the domain the Table belongs to.",
      "type": "string"
    },
    "supportsInterrupt": {
      "description": "If the app run can be interrupted as part of the execution.",
      "type": "boolean",
      "default": false
    }
  },
  "additionalProperties": false
}

=== meta-mart/metamart/metamart-service/src/main/resources/json/data/app/DataInsightsApplication.json
{
  "name": "DataInsightsApplication",
  "displayName": "Data Insights",
  "appConfiguration": {
    "batchSize": 100,
    "recreateDataAssetsIndex": false,
    "backfillConfiguration": {
        "enabled": false
    }
  },
  "appSchedule": {
    "scheduleTimeline": "Custom",
    "cronExpression": "0 3 * * *"
  }
}

=== meta-mart/metamart/metamart-service/src/main/resources/json/data/app/SearchIndexingApplication.json
{
  "name": "SearchIndexingApplication",
  "displayName": "Search Indexing",
  "appConfiguration": {
    "entities": [
      "table",
      "dashboard",
      "topic",
      "pipeline",
      "ingestionPipeline",
      "searchIndex",
      "user",
      "team",
      "glossary",
      "glossaryTerm",
      "mlmodel",
      "tag",
      "classification",
      "query",
      "container",
      "database",
      "databaseSchema",
      "testCase",
      "testSuite",
      "chart",
      "dashboardDataModel",
      "databaseService",
      "messagingService",
      "dashboardService",
      "pipelineService",
      "mlmodelService",
      "storageService",
      "metadataService",
      "searchService",
      "entityReportData",
      "webAnalyticEntityViewReportData",
      "webAnalyticUserActivityReportData",
      "domain",
      "storedProcedure",
      "dataProduct",
      "testCaseResolutionStatus",
      "apiService",
      "apiEndpoint",
      "apiCollection"
    ],
    "recreateIndex": false,
    "batchSize": "100",
    "payLoadSize": 104857600,
    "searchIndexMappingLanguage": "EN"
  },
  "appSchedule": {
    "scheduleTimeline": "Custom",
    "cronExpression": "0 0 * * *"
  },
  "supportsInterrupt": true
}
